# Generated by Django 5.2.7 on 2025-12-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the industry (e.g., Retail, Tailoring, Education)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this industry does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this industry is available for new business registrations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
    ]
