# Generated by Django 5.2.7 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Electronics, Clothing)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='account.business')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when stock falls below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (SKU)', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.business')),
                ('category', models.ForeignKey(help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='retail.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], help_text='Type of inventory change', max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Change in quantity (positive for additions, negative for reductions)')),
                ('previous_quantity', models.IntegerField(help_text='Stock quantity before change')),
                ('new_quantity', models.IntegerField(help_text='Stock quantity after change')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='retail.product')),
            ],
            options={
                'verbose_name': 'Inventory History',
                'verbose_name_plural': 'Inventory Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'name'], name='retail_cate_busines_48349e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='retail_prod_busines_aedfd8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'category'], name='retail_prod_busines_a432ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'sku'], name='retail_prod_busines_725b41_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['product', '-created_at'], name='retail_inve_product_8b15ed_idx'),
        ),
    ]
