# Generated by Django 5.2.7 on 2025-12-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Customer's physical address")),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='account.business')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'phone'], name='customer_cu_busines_290e9f_idx'), models.Index(fields=['business', 'name'], name='customer_cu_busines_7ceaea_idx')],
                'unique_together': {('business', 'phone')},
            },
        ),
    ]
