# Generated by Django 5.2.7 on 2025-12-23 13:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('MENS_SHIRT', "Men's Shirt"), ('MENS_TROUSERS', "Men's Trousers"), ('MENS_SUIT', "Men's Suit"), ('WOMENS_DRESS', "Women's Dress"), ('WOMENS_BLOUSE', "Women's Blouse"), ('WOMENS_SKIRT', "Women's Skirt"), ('TRADITIONAL', 'Traditional Wear'), ('OTHER', 'Other')], help_text='Type of garment these measurements are for', max_length=20)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='Neck measurement', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('chest', models.DecimalField(blank=True, decimal_places=2, help_text='Chest/Bust measurement', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='Waist measurement', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hips', models.DecimalField(blank=True, decimal_places=2, help_text='Hips measurement', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, help_text='Shoulder width', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, help_text='Sleeve length', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, help_text='Inseam (for trousers)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='Garment length', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes (fit preferences, adjustments, etc.)')),
                ('date_taken', models.DateField(help_text='Date when measurements were taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this measurement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='account.business')),
                ('customer', models.ForeignKey(help_text='The customer these measurements belong to', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('MENS_SHIRT', "Men's Shirt"), ('MENS_TROUSERS', "Men's Trousers"), ('MENS_SUIT', "Men's Suit"), ('WOMENS_DRESS', "Women's Dress"), ('WOMENS_BLOUSE', "Women's Blouse"), ('WOMENS_SKIRT', "Women's Skirt"), ('TRADITIONAL', 'Traditional Wear'), ('OTHER', 'Other')], help_text='Type of garment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Task description (fabric details, style, special requests)')),
                ('due_date', models.DateField(help_text='When this task should be completed')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_FITTING', 'Ready for Fitting'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='NOT_STARTED', help_text='Current status of the task', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this task/order', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid', models.BooleanField(default=False, help_text='Whether payment has been received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_tasks', to='account.business')),
                ('customer', models.ForeignKey(help_text='The customer this task is for', on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_tasks', to='customer.customer')),
                ('measurement', models.ForeignKey(blank=True, help_text='Associated measurement (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tailoring.measurement')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['business', 'customer'], name='tailoring_m_busines_f4c33e_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['business', 'garment_type'], name='tailoring_m_busines_f32cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'status'], name='tailoring_t_busines_deb89e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'due_date'], name='tailoring_t_busines_743e20_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'customer'], name='tailoring_t_busines_06b820_idx'),
        ),
    ]
